
server:
  port: 8083
spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/secondhand_exchange?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hxh110120
    druid:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false

      initial-size: 10

      max-wait: 60000

      max-active: 20

      min-idle: 10

      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

      time-between-eviction-runs-millis: 60000

      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'

      remove-abandoned: true
      remove-abandoned-timeout: 1800

      log-abandoned: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: false

  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml


pagehelper:

  offset-as-page-num: true

  row-bounds-with-count: true

  page-size-zero: true

  reasonable: true

  params: pageNum=start;pageSize=limit;

  support-methods-arguments: true


logging:
  level:
    com.company.exchange: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug